#!/usr/bin/env python3
"""Tasks 5.1–5.2 — emit the approval table: one row per in-scope site image.

Joins three inputs:
  site-images.json   what the database currently shows (the baseline)
  provenance.json    which deck each image came from, and who owns that deck
  verdicts.json      the reviewer's decision, for images that are not a plain keep

Every in-scope image gets a row whether or not it was flagged, so a skipped image
is visible as a missing row rather than as a silent absence. Images with no entry
in verdicts.json default to `keep` with a provenance-derived reason.

Verdict keys in verdicts.json are `slug/filename`, or `slug/filename@field` when
one file appears in two fields on the same study and the two uses differ — which
happens once, where FoodSaver's cover is reused as a pillar creative.

Usage: scripts/case-studies/build_table.py [--out FILE.md]
"""

import json
import os
import sys
from collections import Counter, defaultdict

AUDIT = os.environ.get("AUDIT_ROOT", "/mnt/work/goodone/.cs-audit")


def main():
    out = None
    if "--out" in sys.argv:
        out = sys.argv[sys.argv.index("--out") + 1]

    site = json.load(open(os.path.join(AUDIT, "site-images.json")))
    prov = {
        (r["slug"], r["field"]): r
        for r in json.load(open(os.path.join(AUDIT, "provenance.json")))["images"]
    }
    verdicts = json.load(open(os.path.join(AUDIT, "verdicts.json")))["images"]
    pool = json.load(open(os.path.join(AUDIT, "pool-filter.json")))["perClient"]

    rows = []
    for s in site["studies"]:
        for im in s["images"]:
            if not im["inScope"]:
                continue
            key = f"{s['slug']}/{im['filename']}"
            v = verdicts.get(f"{key}@{im['field']}") or verdicts.get(key)
            p = prov.get((s["slug"], im["field"]), {})
            if v:
                verdict, cls = v["verdict"], v.get("class", "")
                reason, repl = v["reason"], v.get("replacement") or "—"
            else:
                verdict, cls = "keep", "client-own"
                owner = p.get("poolSpread") or []
                if p.get("matchedDeck"):
                    reason = (
                        f"traced to {s['slug']}'s own deck "
                        f"(d={p.get('distance')}), no other client holds it"
                        if owner == [s["slug"]]
                        else f"traced to deck {p.get('matchedDeck')} (d={p.get('distance')})"
                    )
                else:
                    reason = (
                        "no deck match; reviewed visually and depicts the client's "
                        "own brand, product, people or communication"
                    )
                repl = "—"
            rows.append(
                {
                    "slug": s["slug"],
                    "client": s["client"],
                    "field": im["field"],
                    "mediaId": im["mediaId"],
                    "filename": im["filename"],
                    "verdict": verdict,
                    "class": cls,
                    "reason": reason,
                    "replacement": repl,
                }
            )

    assert len(rows) == site["totals"]["inScope"], (
        f"row count {len(rows)} != in-scope {site['totals']['inScope']}"
    )

    counts = Counter(r["verdict"] for r in rows)
    classes = Counter(r["class"] for r in rows if r["verdict"] != "keep")

    # per-section counts after removals (task 4.5)
    before = defaultdict(int)
    after = defaultdict(int)
    for r in rows:
        before[r["slug"]] += 1
        if r["verdict"] != "remove":
            after[r["slug"]] += 1

    lines = [
        "# Case-study imagery audit — approval table",
        "",
        "Generated by `scripts/case-studies/build_table.py`. One row per in-scope",
        "image (cover + `approach[].media`); the `gallery` field is empty on every",
        "study, so it contributes no rows.",
        "",
        f"**{len(rows)}** images reviewed across **{len(before)}** studies: "
        f"**{counts['remove']}** remove, **{counts['keep-note']}** keep-with-note, "
        f"**{counts['keep']}** keep.",
        "",
        "## Removals and notes",
        "",
        "| Study | Field | Media | File | Verdict | Class | Reason | Replacement |",
        "| --- | --- | ---: | --- | --- | --- | --- | --- |",
    ]
    for r in rows:
        if r["verdict"] == "keep":
            continue
        lines.append(
            f"| `{r['slug']}` | `{r['field']}` | {r['mediaId']} | `{r['filename']}` "
            f"| **{r['verdict']}** | {r['class']} | {r['reason']} | {r['replacement']} |"
        )

    lines += [
        "",
        "## Section counts after removal",
        "",
        "| Study | Now | After | Pool available |",
        "| --- | ---: | ---: | ---: |",
    ]
    for slug in sorted(before):
        if before[slug] == after[slug]:
            continue
        avail = pool.get(slug, {}).get("keep", 0)
        warn = "  ⚠ thin" if avail < 4 else ""
        lines.append(f"| `{slug}` | {before[slug]} | {after[slug]} | {avail}{warn} |")

    lines += ["", "## Every image", "",
              "| Study | Field | Media | File | Verdict | Reason |",
              "| --- | --- | ---: | --- | --- | --- |"]
    for r in rows:
        lines.append(
            f"| `{r['slug']}` | `{r['field']}` | {r['mediaId']} | `{r['filename']}` "
            f"| {r['verdict']} | {r['reason']} |"
        )

    text = "\n".join(lines) + "\n"
    if out:
        open(out, "w").write(text)
        print(f"wrote {out}")
    else:
        print(text)

    print(f"\n{len(rows)} rows — matches in-scope total {site['totals']['inScope']}")
    print("verdicts:", dict(counts))
    print("classes :", dict(classes))
    shrink = {s: (before[s], after[s]) for s in before if before[s] != after[s]}
    print(f"studies losing images: {len(shrink)}")
    for s, (b, a) in sorted(shrink.items()):
        avail = pool.get(s, {}).get("keep", 0)
        print(f"  {s:24} {b} -> {a}   pool={avail}")


if __name__ == "__main__":
    main()
